# Generated by Django 4.2.7 on 2023-12-28 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_habitunit_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodcategory',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.periodcategory'),
        ),
    ]
