# Generated by Django 5.0.1 on 2024-01-18 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_periodcategory_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.habitcategory'),
        ),
        migrations.AlterField(
            model_name='periodcategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.periodcategory'),
        ),
    ]
