# Generated by Django 4.2.7 on 2023-12-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0002_unit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='clock.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='clock.category', verbose_name='Category'),
        ),
    ]
