# Generated by Django 4.2.7 on 2023-12-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0003_alter_category_parent_alter_unit_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
