# Generated by Django 4.2.7 on 2023-12-13 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clock', '0004_alter_unit_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='duration',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
